Repository Cumulonimbus-Cloud/client-react, pull requests merged in 2024-06, with the labels that each got.

#6 [UI/#4] 메인 페이지 구현
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/assets/main/icon_transcript.svg
  src/assets/main/icon_upload.svg
  src/assets/main/index.js
  src/components/main/Description.css
  src/components/main/Description.js
  src/components/main/ExampleQuestion.js
  src/components/main/QuestionElem.css
  src/components/main/QuestionElem.js
  src/components/main/UploadBtn.css
  src/components/main/UploadBtn.js
  src/components/main/index.js
  src/index.js
  src/pages/Main.css
  src/pages/Main.js
  src/pages/index.js
Labels: UI

#7 [UI/#5] 헤더 바 구현
  package-lock.json
  package.json
  src/App.js
  src/assets/header/icon_logo.svg
  src/assets/header/icon_question_mark.svg
  src/assets/header/icon_x.svg
  src/assets/header/index.js
  src/components/header/ContentElem.js
  src/components/header/Header.css
  src/components/header/Header.js
  src/components/header/Modal.css
  src/components/header/Modal.js
  src/components/header/ModalContent.css
  src/components/header/ModalContent.js
  src/pages/Main.css
Labels: UI

#9 [Feat/#8] 카카오 로그인 구현
  src/App.js
  src/assets/main/icon_kakao_logo.svg
  src/assets/main/index.js
  src/components/login/KakaoRedirect.css
  src/components/login/KakaoRedirect.js
  src/components/login/LoginBtn.css
  src/components/login/LoginBtn.js
  src/components/login/index.js
  src/components/main/MainContents.js
  src/components/main/index.js
  src/pages/Main.js
Labels: UI, FEAT

#14 [ Fix/#12] kakao redirect시 화면 설정
  src/App.js
Labels: FIX

#15 [UI/#13] 세부 버튼 구현
  src/App.js
  src/assets/main/icon_chatting.svg
  src/assets/main/index.js
  src/components/main/MainContents.css
  src/components/main/MainContents.js
  src/components/main/buttons/ChattingBtn.css
  src/components/main/buttons/ChattingBtn.js
  src/components/main/buttons/EditBtn.css
  src/components/main/buttons/EditBtn.js
  src/components/main/buttons/UploadBtn.css
  src/components/main/buttons/UploadBtn.js
  src/components/main/buttons/index.js
  src/components/main/index.js
  src/pages/Main.css
  src/pages/Main.js
Labels: UI

#17 [Fix/#16] 상태 초기화
  src/App.js
Labels: FIX

#20 [Tese/#19] redirect 라우트 설정
  src/App.js
  src/components/login/KakaoRedirect.js
Labels: TEST

#21 [UI/#18] 채팅 페이지 구현
  src/App.js
  src/components/chat/ChatElem.css
  src/components/chat/ChatElem.js
  src/components/chat/index.js
  src/pages/Chat.css
  src/pages/Chat.js
  src/pages/index.js
Labels: UI

#23 [Feat/#22] 성적표 파일 업로드
  src/App.js
  src/components/main/MainContents.js
  src/components/main/buttons/UploadBtn.js
  src/index.js
  src/pages/Main.js
Labels: FEAT

#25 [Feat/#24] 성적표 수정 기능
  src/components/main/MainContents.js
  src/components/main/buttons/ChattingBtn.css
  src/components/main/buttons/ChattingBtn.js
  src/components/main/buttons/EditBtn.css
  src/components/main/buttons/EditBtn.js
Labels: FEAT

#28 [Fix/#27] 성적표 업로드 API 연결
  src/components/main/buttons/UploadBtn.js
Labels: FIX

#30 [Refactor/#29] 로그 정리
  src/App.js
  src/components/main/buttons/UploadBtn.js
  src/pages/Main.js
Labels: REFACTOR

#32 [Fix/#31] 파일 업로드 API 연결
  src/components/main/buttons/EditBtn.js
  src/components/main/buttons/UploadBtn.js
Labels: FIX

#33 [Feat/#26] 챗봇 기능
  src/App.js
  src/components/chat/ChatElem.css
  src/components/chat/ChatElem.js
  src/components/chat/QuestionList.css
  src/components/chat/QuestionList.js
  src/components/chat/index.js
  src/components/main/buttons/ChattingBtn.css
  src/components/main/buttons/ChattingBtn.js
  src/pages/Chat.js
Labels: FEAT

#39 [Feat/#37] 로그인 토큰 localstorage에 저장
  src/App.js
  src/components/login/KakaoRedirect.js
Labels: FEAT

#40 [Feat/#38] 성적표 유무에 따라 화면 이동
  src/App.js
  src/components/login/KakaoRedirect.js
Labels: FEAT

#42 [Fix/#41] 성적표 유무에 따라 화면 이동
  src/App.js
  src/components/login/KakaoRedirect.js
Labels: FIX

#44 [Fix/#43] 오타 수정
  src/components/login/KakaoRedirect.js
Labels: FIX

#45 [Feat/#36] 챗봇 API 연결
  src/components/chat/QuestionList.js
  src/pages/Chat.js
Labels: FEAT

#47 [Fix/#46] 챗봇 대화 수정
  src/components/chat/ChatElem.js
  src/components/chat/QuestionList.js
Labels: FIX

#54 [Feat/#48] 챗봇 기타 자유질문 기능
  src/assets/header/icon_logo_white.svg
  src/assets/header/index.js
  src/components/chat/QuestionList.css
  src/components/chat/QuestionList.js
Labels: FEAT

#57 [Fix/#56] 질문 API 연결 오타 수정
  src/components/chat/QuestionList.js
Labels: FIX

#58 [Feat/#52] 로그아웃 기능
  src/App.js
  src/assets/header/icon_logout.svg
  src/assets/header/index.js
  src/components/chat/QuestionList.js
  src/components/header/Header.css
  src/components/header/Header.js
  src/components/header/LogoutContent.css
  src/components/header/LogoutContent.js
  src/components/header/Modal.js
Labels: FEAT

#59 [Design/#49] 로고 수정
  public/favicon_induck_bot.ico
  public/index.html
  src/assets/header/icon_logo.svg
  src/assets/header/icon_logo_old.svg
  src/components/header/Header.css
  src/components/header/Header.js
Labels: DESIGN

#60 [Update/#51] 도움말 팝업 내용 수정
  src/components/header/Modal.js
  src/components/header/ModalContent.js
Labels: UPDATE

#61 [Feat/#53] 이전 페이지 이동 기능
  src/components/header/Header.css
Labels: FEAT

#63 [Test/#62] 이전 페이지 버튼 테스트
  src/App.js
  src/assets/header/icon_prev_btn.svg
  src/assets/header/index.js
  src/components/header/Header.js
  src/pages/Chat.js
  src/pages/Main.js
Labels: TEST

#64 [Feat/#50] 파일 업로드 후 팝업 기능
  src/components/header/EditModal.js
  src/components/header/Modal.js
  src/components/header/UploadModal.js
  src/components/main/buttons/EditBtn.js
  src/components/main/buttons/UploadBtn.js
Labels: FEAT

#65 [Feat/#55] 답변 로딩 중일 때 동적 효과 기능
  src/components/chat/ChatElem.js
  src/components/chat/QuestionList.js
Labels: FEAT

#67 [Refactor/#56] 로고 수정
  src/assets/header/icon_logo_old2.svg
  src/assets/header/induck_logo.svg
Labels: REFACTOR

#68 [Refactor/#56] 로고 수정
  src/assets/header/icon_logo.svg
Labels: REFACTOR

#69 [Refactor/#56] 로고 수정
  src/assets/header/icon_logo.svg
  src/assets/header/icon_logo_old2.svg
Labels: REFACTOR
